### ISSUE TITLE
download sample records

### ISSUE THREAD

**Issue by alby1976** [UofC-Research/peer-review#1]
```[tasklist]
### Tasks
- [ ] https://github.com/UofC-Research/peer-review/issues/2
- [ ] https://github.com/UofC-Research/peer-review/issues/4
- [ ] https://github.com/UofC-Research/peer-review/issues/5
```
